### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by takebayashi**
It's the same problem as uber/uReplicator#7

### CODE REVIEW

**Comment by takebayashi** [comment]
I signed.

**Comment by cloudXane** [comment]
hi @takebayashi thanks for the fix, I'm curious why the build works on my side. Could you please post the error msg you encountered here. Thanks for the help!

**Comment by takebayashi** [comment]
@cloudXane 
I tried to build using Maven 3.3.9 without any custom configurations, but faced the following error messages:
```
mvn clean package -DskipTests
...
(snip)
...                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ChaperoneServiceController 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.jacoco:jacoco-maven-plugin:jar:0.7.6-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Chaperone .......................................... SUCCESS [  0.491 s]
[INFO] ChaperoneServiceController ......................... FAILURE [  0.021 s]
[INFO] ChaperoneServiceWorker ............................. SKIPPED
[INFO] ChaperoneClient .................................... SKIPPED
[INFO] ChaperoneCollector ................................. SKIPPED
[INFO] ChaperoneDistribution .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.716 s
[INFO] Finished at: 2017-01-07T09:59:33+09:00
[INFO] Final Memory: 8M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.jacoco:jacoco-maven-plugin:0.7.6-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.jacoco:jacoco-maven-plugin:jar:0.7.6-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by cloudXane** [comment]
Got it. Thanks for the info and the pull request. Merged.

**Pull request merged**
